/**
 * Module with the app actions.
 * @module src/constants/actions
 */
// Form Rules.
export const UPDATE_RULES_VALIDATION = 'UPDATE_RULES_VALIDATION';
export const CLEAR_RULES_VALIDATION = 'CLEAR_RULES_VALIDATION';

// User.
export const AUTH_USER = 'AUTH_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

// Common.
export const CLEAR_CURRENT_SCREEN_DATA = 'CLEAR_CURRENT_SCREEN_DATA';
export const HIDE_LOADING = 'HIDE_LOADING';
export const HIDE_TOAST = 'HIDE_TOAST';
export const INIT_CURRENT_SCREEN = 'INIT_CURRENT_SCREEN';
export const INIT_NET_WATCHER = 'INIT_NET_WATCHER';
export const SET_ORDER = 'SET_ORDER';
export const SET_SCREEN_DEFAULT_STATE = 'SET_SCREEN_DEFAULT_STATE';
export const SET_SCREEN_LOADED = 'SET_SCREEN_LOADED';
export const SET_STORE_UPDATED = 'SET_STORE_UPDATED';
export const SHOW_LOADING = 'SHOW_LOADING';
export const SHOW_TOAST = 'SHOW_TOAST';
export const UPDATE_LOADING_LABEL = 'UPDATE_LOADING_LABEL';
export const UPDATE_STORE = 'UPDATE_STORE';

// Login.
export const CLEAR_LOGIN_FORM = 'CLEAR_LOGIN_FORM';
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const UPDATE_LOGIN_FORM = 'UPDATE_LOGIN_FORM';

// Orders.
export const ADD_PICTURE_TO_ORDER = 'ADD_PICTURE_TO_ORDER';
export const CLEAR_ORDERS = 'CLEAR_ORDERS';
export const DELIVER_ORDER = 'DELIVER_ORDER';
export const DELIVER_ORDER_PARTIALLY = 'DELIVER_ORDER_PARTIALLY';
export const DELIVER_ORDER_SUCCESS = 'DELIVER_ORDER_SUCCESS';
export const INIT_ORDERS = 'INIT_ORDERS';
export const SYNC_ORDERS = 'SYNC_ORDERS';
export const SET_ORDER_TO_NOT_DELIVERED = 'SET_ORDER_TO_NOT_DELIVERED';
export const NOTIFY_NOT_DELIVERED_ORDER = 'SUBMIT_NOT_DELIVERED_ORDER';
export const UPDATE_ORDER_MESSAGE = 'UPDATE_ORDER_MESSAGE';
export const SYNCED_ORDERS = 'SYNCED_ORDERS';

// Picture Preview.
export const CLEAR_PICTURE_PREVIEW = 'CLEAR_PICTURE_PREVIEW';
export const CLEAR_PICTURE_URI = 'CLEAR_PICTURE_URI';
export const CLEAR_RETAKE_PICTURE = 'CLEAR_RETAKE_PICTURE';
export const SET_PICTURE_TO_PREVIEW = 'SET_PICTURE_TO_PREVIEW';
export const SET_PICTURE_TYPE = 'SET_PICTURE_TYPE';
export const SET_PICTURE_URI = 'SET_PICTURE_URI';
export const SET_RETAKE_PICTURE = 'SET_RETAKE_PICTURE';
export const SHOT_PICTURE = 'SHOT_PICTURE';
export const STORE_PICTURE = 'STORE_PICTURE';
